image: registry.gitlab.tugraz.at/dbp/topics/common/main:v1

cache:
  key: ${CI_PROJECT_PATH}
  paths:
    - _npm_cache

before_script:
  - 'git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tugraz.at/".insteadOf "git@gitlab.tugraz.at:"'
  - git submodule sync
  - git submodule update --init
  - npm config set cache "$CI_PROJECT_DIR/_npm_cache"

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm ci
    - npm run test

linting:
  allow_failure: true
  stage: test
  script:
    - npm ci
    - npm run lint

#publish:
#  stage: deploy
#  only:
#    refs:
#      - deploy
#      - main
#  script:
#    # https://www.npmjs.com/settings/dbp-deploy/tokens
#    # NPM_TOKEN needs to be a "Publish" token with 2FA disabled!
#    # "Automation" tokens don't work with lerna (even if they would work with "npm publish")
#    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
#    - npm ci
#    - npm run build
#    - npm run publish

deploy:
  stage: deploy
  except:
    - schedules
  only:
    refs:
      - main
      - demo
  inherit:
    variables: false
  variables:
    UPSTREAM_PROJECT_PATH: ${CI_PROJECT_PATH}
    UPSTREAM_COMMIT_BRANCH: ${CI_COMMIT_BRANCH}
    UPSTREAM_COMMIT_SHA: ${CI_COMMIT_SHA}
  trigger:
    project: dbp/deployer
    strategy: depend
