export default {
    local: {
        basePath: '/dist/',
        entryPointURL: 'http://127.0.0.1:8000',
        keyCloakBaseURL: 'https://auth-dev.tugraz.at/auth',
        keyCloakRealm: 'tugraz-vpu',
        keyCloakClientId: 'auth-dev-mw-frontend-local',
        matomoUrl: 'https://analytics.tugraz.at/',
        matomoSiteId: 131,
        nextcloudBaseURL: 'https://cloud-dev.tugraz.at',
        nextcloudName: 'TU Graz cloud',
        siteName: 'TU Graz',
        siteSubName: 'Graz University of Technology',
    },
    development: {
        basePath: '/apps/activity-showcase/',
        entryPointURL: 'https://api-dev.tugraz.at',
        keyCloakBaseURL: 'https://auth-dev.tugraz.at/auth',
        keyCloakRealm: 'tugraz-vpu',
        keyCloakClientId: 'dbp-activity-showcase',
        matomoUrl: 'https://analytics.tugraz.at/',
        matomoSiteId: 131,
        nextcloudBaseURL: 'https://cloud-dev.tugraz.at',
        nextcloudName: 'TU Graz cloud',
        siteName: 'TU Graz',
        siteSubName: 'Graz University of Technology',
    },
    demo: {
        basePath: '/apps/activity-showcase/',
        entryPointURL: 'https://api-demo.tugraz.at',
        keyCloakBaseURL: 'https://auth-demo.tugraz.at/auth',
        keyCloakRealm: 'tugraz-vpu',
        keyCloakClientId: 'dbp-activity-showcase',
        matomoUrl: 'https://analytics.tugraz.at/',
        matomoSiteId: 131,
        nextcloudBaseURL: 'https://cloud-demo.tugraz.at',
        nextcloudName: 'TU Graz cloud',
        siteName: 'TU Graz',
        siteSubName: 'Graz University of Technology',
    },
    staging: {
        basePath: '/',
        entryPointURL: 'https://api-test.tugraz.at',
        keyCloakBaseURL: 'https://auth-test.tugraz.at/auth',
        keyCloakRealm: 'tugraz',
        keyCloakClientId: 'dbp-activity-showcase',
        matomoUrl: 'https://analytics.tugraz.at/',
        matomoSiteId: 131,
        nextcloudBaseURL: 'https://cloud-demo.tugraz.at',
        nextcloudName: 'TU Graz cloud',
        siteName: 'TU Graz',
        siteSubName: 'Graz University of Technology',
    },
    production: {
        basePath: '/',
        entryPointURL: 'https://api.tugraz.at',
        keyCloakBaseURL: 'https://auth.tugraz.at/auth',
        keyCloakRealm: 'tugraz',
        keyCloakClientId: 'dbp-activity-showcase',
        matomoUrl: 'https://analytics.tugraz.at/',
        matomoSiteId: 131,
        nextcloudBaseURL: 'https://cloud.tugraz.at',
        nextcloudName: 'TU Graz cloud',
        siteName: 'TU Graz',
        siteSubName: 'Graz University of Technology',
    },
};
